import { useState } from "react";
import { HelpCircle, Search, ChevronDown, ChevronUp } from "lucide-react";

interface ExplainerItem {
  term: string;
  definition: string;
  whyItMatters: string;
  formula?: string;
  example: string;
}

const EXPLAINERS: ExplainerItem[] = [
  {
    term: "Revenue (Sales)",
    definition: "Revenue represents the gross income generated by a company through its core business activities, such as selling goods or delivering services.",
    whyItMatters: "Consistent revenue growth over time indicates that the company is expanding its market reach, launching successful products, or finding new customers.",
    example: "If a company sells 10,000 cars at ₹10 Lakh each, its annual revenue is ₹1,000 Crore before accounting for any expenses."
  },
  {
    term: "Debt (Borrowings)",
    definition: "Debt refers to borrowed capital that the company must repay in the future, typically carrying interest obligations.",
    whyItMatters: "A reasonable debt level facilitates expansion, but excessive debt creates high interest expense, reducing net margins and increasing bankruptcy risk during economic slowdowns.",
    formula: "Debt-to-Equity Ratio = Total Liabilities / Shareholder Equity",
    example: "A Debt-to-Equity ratio of 0.3 means for every ₹1.00 of equity owned by shareholders, the company has borrowed ₹0.30."
  },
  {
    term: "Return on Equity (ROE)",
    definition: "ROE measures the profitability of a business in relation to the book value of its shareholder equity.",
    whyItMatters: "It illustrates how efficiently management is generating profits using the money invested by common stockholders. Ratios above 15-20% are considered premium.",
    formula: "ROE = (Net Income / Shareholder Equity) * 100",
    example: "An ROE of 22% implies the company successfully generates ₹22 in net profit for every ₹100 of equity capital invested."
  },
  {
    term: "Return on Capital Employed (ROCE)",
    definition: "ROCE measures a company's profitability and capital efficiency by comparing its operating income to the total capital invested (both equity and long-term debt).",
    whyItMatters: "It is a better measure than ROE for capital-intensive sectors because it incorporates debt. If ROCE is lower than the interest rates the company pays to borrow, capital is being destroyed.",
    formula: "ROCE = (EBIT / Capital Employed) * 100",
    example: "If ROCE is 26%, it means the business earns ₹26 of operating profit on every ₹100 of combined debt and equity capital utilized."
  },
  {
    term: "Stock P/E Ratio",
    definition: "The Price-to-Earnings (P/E) ratio compares the current market price of a stock to its annual earnings per share.",
    whyItMatters: "It indicates how many multiples of earnings investors are willing to pay to own one share. Comparing it against the Industry P/E reveals if the stock is undervalued or expensive.",
    formula: "P/E Ratio = Market Price per Share / Earnings per Share (EPS)",
    example: "A P/E of 25 means investors are paying ₹25 for every ₹1 of current net profit. If the industry average is 15, the stock may be priced at a premium."
  },
  {
    term: "Book Value",
    definition: "Book value represents the net asset value of a company, calculated as total assets minus all liabilities. It represents what shareholders would receive if the company liquidated tomorrow.",
    whyItMatters: "Investors use the Price-to-Book (P/B) ratio to check if a stock is trading near its physical value. Conservative investors prefer stocks with moderate P/B ratios.",
    formula: "Book Value per Share = Net Asset Value / Total Outstanding Shares",
    example: "If a company has assets of ₹500 Cr and liabilities of ₹200 Cr, its net book value is ₹300 Cr. With 3 Crore shares, the Book Value per Share is ₹100."
  },
  {
    term: "CAGR (Compound Annual Growth Rate)",
    definition: "CAGR calculates the smoothed annual growth rate of a financial metric (like Sales or Profit) over a multi-year period, removing yearly volatility.",
    whyItMatters: "It provides a clear picture of long-term trajectories instead of looking at erratic single-year percentage jumps.",
    formula: "CAGR = ((Ending Value / Beginning Value) ^ (1 / Years)) - 1",
    example: "If sales grew from ₹100 Cr to ₹144 Cr in 2 years, the CAGR is 20% per year (not a simple average of percentages)."
  },
  {
    term: "Intrinsic Value (DCF)",
    definition: "Intrinsic value is the 'fair' or actual value of a stock calculated based on the present value of all its projected future cash flows.",
    whyItMatters: "If the intrinsic value is higher than the current stock price, the stock is undervalued and offers a 'Margin of Safety'.",
    example: "If the DCF model estimates the fair value of a share at ₹1,200, and it is currently trading at ₹900, the stock has a 25% Margin of Safety."
  },
  {
    term: "Piotroski Score",
    definition: "The Piotroski Score is a 9-point score designed to evaluate the financial strength of a company using nine criteria on its balance sheet and income statement.",
    whyItMatters: "A score of 7-9 reflects excellent financial strength, whereas 0-3 suggests high risk of financial distress or accounting weakness.",
    example: "A company gets points for positive net income, positive cash flow, debt reduction, and increasing profit margins. A score of 8/9 is excellent."
  },
  {
    term: "Altman Z-Score",
    definition: "The Altman Z-Score is a credit-strength formula that predicts the probability that a business will go bankrupt within two years.",
    whyItMatters: "Scores above 3.0 place the company in the Safe Zone. Scores below 1.8 signify distress and high insolvency risks.",
    example: "A company with stable sales, low borrowings, and positive working capital gets a score of 3.4 (Safe Zone)."
  },
  {
    term: "Graham Number",
    definition: "Named after Benjamin Graham (the father of value investing), this number represents the maximum defensive price an investor should pay for a stock.",
    whyItMatters: "It combines book value and earnings to find a baseline value, ensuring you don't overpay for hype.",
    formula: "Graham Number = Square Root of (22.5 * Earnings Per Share * Book Value Per Share)",
    example: "If EPS is ₹50 and Book Value is ₹200, the Graham Number is √(22.5 * 50 * 200) = ₹474.34. Pay less than this for safety."
  },
  {
    term: "Free Cash Flow (FCF)",
    definition: "Free Cash Flow is the cash left over after a company pays for its operating expenses and capital expenditures (buying equipment, building factories).",
    whyItMatters: "Unlike net profit (which is an accounting figure), cash is real money. FCF is used to repay debt, distribute dividends, and fund acquisitions.",
    formula: "Free Cash Flow = Cash from Operations - Capital Expenditures",
    example: "If a company generates ₹500 Cr in cash from sales but spends ₹200 Cr building a new plant, its Free Cash Flow is ₹300 Cr."
  },
  {
    term: "Operating Profit Margin (OPM %)",
    definition: "OPM measures the percentage of revenue left over after paying for variable costs of production, wages, and raw materials.",
    whyItMatters: "High margins indicate pricing power and cost leadership, meaning the company can easily withstand raw material price hikes.",
    formula: "OPM % = (Operating Profit / Total Revenue) * 100",
    example: "An OPM of 25% means the company earns ₹25 in operating profit on every ₹100 of sales before interest and taxes."
  }
];

export function AIExplanationPanel() {
  const [search, setSearch] = useState("");
  const [expandedTerms, setExpandedTerms] = useState<string[]>(EXPLAINERS.map((item) => item.term));

  const toggleTerm = (term: string) => {
    if (expandedTerms.includes(term)) {
      setExpandedTerms(expandedTerms.filter((t) => t !== term));
    } else {
      setExpandedTerms([...expandedTerms, term]);
    }
  };

  const filtered = EXPLAINERS.filter(
    (item) =>
      item.term.toLowerCase().includes(search.toLowerCase()) ||
      item.definition.toLowerCase().includes(search.toLowerCase())
  );

  return (
    <div className="glass-panel p-6 rounded-2xl">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-6">
        <div>
          <h3 className="text-sm font-bold text-slate-300 uppercase tracking-wider flex items-center gap-2">
            <HelpCircle className="w-4.5 h-4.5 text-emeraldGreen" />
            AI Financial Terminology Guide
          </h3>
          <p className="text-[11px] text-slate-400 mt-1 font-light leading-relaxed">
            Understand key fundamental metrics and calculation methods.
          </p>
        </div>

        {/* Search Filter */}
        <div className="relative max-w-xs w-full">
          <Search className="absolute left-3 top-2.5 w-4 h-4 text-slate-500" />
          <input
            type="text"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            placeholder="Search metric..."
            className="w-full bg-darkCard border border-darkBorder focus:border-emeraldGreen/50 focus:outline-none rounded-xl pl-9 pr-4 py-2 text-xs font-semibold placeholder-slate-500 text-white"
          />
        </div>
      </div>

      <div className="flex flex-col gap-3">
        {filtered.map((item, idx) => {
          const isExpanded = expandedTerms.includes(item.term);
          return (
            <div 
              key={idx}
              className="border border-darkBorder rounded-xl bg-darkCard/30 overflow-hidden transition-colors"
            >
              <button
                onClick={() => toggleTerm(item.term)}
                className="w-full px-5 py-4 flex items-center justify-between text-left hover:bg-darkCard/70 transition-colors cursor-pointer"
              >
                <span className="text-xs sm:text-sm font-bold text-white tracking-wider">{item.term}</span>
                {isExpanded ? (
                  <ChevronUp className="w-4 h-4 text-slate-400" />
                ) : (
                  <ChevronDown className="w-4 h-4 text-slate-400" />
                )}
              </button>

              {isExpanded && (
                <div className="px-5 pb-5 pt-1 border-t border-darkBorder/40 flex flex-col gap-4 text-xs font-light text-slate-300 leading-relaxed bg-darkCard/10 animate-fade-in">
                  <div>
                    <span className="font-bold text-emeraldGreen block mb-1 text-[10px] uppercase tracking-wider">Definition</span>
                    <p>{item.definition}</p>
                  </div>
                  
                  <div>
                    <span className="font-bold text-blue-400 block mb-1 text-[10px] uppercase tracking-wider">Why It Matters</span>
                    <p>{item.whyItMatters}</p>
                  </div>

                  {item.formula && (
                    <div className="p-3 rounded-lg bg-darkBg border border-darkBorder/60 font-mono text-[11px] text-slate-200">
                      <span className="font-bold text-purple-400 block mb-1.5 text-[9px] uppercase tracking-wider font-sans">Formula</span>
                      {item.formula}
                    </div>
                  )}

                  <div>
                    <span className="font-bold text-goldYellow block mb-1 text-[10px] uppercase tracking-wider">Example Scenario</span>
                    <p className="italic">"{item.example}"</p>
                  </div>
                </div>
              )}
            </div>
          );
        })}

        {filtered.length === 0 && (
          <div className="text-center py-8 text-xs text-slate-500 font-medium">
            No metrics matching "{search}" were found.
          </div>
        )}
      </div>
    </div>
  );
}
